spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.20.238:50514/sinabro?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: user012
  jpa:
    generate-ddl: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernates:
      ddl-auto: update
    show-sql: "true"
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: "9000"
