spring:
  datasource:
    username: user
    url: jdbc:mysql://52.78.11.161:58448/sinabro?createDatabaseIfNotExist=true
    password: user012
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernates:
      ddl-auto: update
    show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: '9000'
